### ISSUE TITLE
[BUG] Liked songs heart isn't centered

### ISSUE THREAD

**Issue by Wist9063** [JulienMaille/dribbblish-dynamic-theme#51] opened 2021-10-06 05:10 UTC
**Describe the bug**
The heart for the liked songs on the left side isn't centered.

**Screenshots**
![image](https://user-images.githubusercontent.com/22089269/136143729-1c224e97-e6f9-4356-b0f9-5a452e89ce59.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - Version: 2.2
 - Spicetify Verison: 2.7.0

**Logs**
![image](https://user-images.githubusercontent.com/22089269/136143934-9e6c0347-d726-4bb7-a79f-d12be1c8be36.png)

**Comment by WelkinBunbury** [comment] 2021-10-06 05:29
create playlist is also not centered
![image](https://user-images.githubusercontent.com/33565456/136145635-54e0e757-6ab8-4e56-8bd9-ce503bb99592.png)

**Comment by SendNukez** [comment] 2021-10-06 10:19
I'll look into it.

**Comment by JulienMaille** [comment] 2021-10-06 10:50
I think the bug is in spicetify css map

**Comment by SendNukez** [comment] 2021-10-06 11:07
Looks like this went by me because I'm using the minnimized sidebar, could you try replacing user.css with [this](https://gist.github.com/SendNukez/9fc8af29123133929d00a28aac93bcc9), and then running `spicetify apply` and tell me if it fixes it

**Comment by SendNukez** [comment] 2021-10-06 12:02
The text was misaligned for me, but not the icons. And the Liked songs had no hover, wich I think is what caused the wist's bug, because they have different classes and I didn't notice because I have it hidden.

**Comment by Wist9063** [comment] 2021-10-07 04:41
> 
> 
> Looks like this went by me because I'm using the minimized sidebar, could you try replacing user.css with [this](https://gist.github.com/SendNukez/9fc8af29123133929d00a28aac93bcc9), and then running `spicetify apply` and tell me if it fixes it

I've applied it and it's still apparent. 

![image](https://user-images.githubusercontent.com/22089269/136321415-af4f9f87-4692-4c3f-ab06-ff705755d920.png) ![image](https://user-images.githubusercontent.com/22089269/136321428-2869c79e-d2bf-461a-abd8-2d121b44c3ee.png)

**Comment by SendNukez** [comment] 2021-10-07 04:47
that's odd. What Spotify version are you using?

**Comment by Wist9063** [comment] 2021-10-07 05:24
> 
> 
> that's odd. What Spotify version are you using?

1.1.69.612

![image](https://user-images.githubusercontent.com/22089269/136324825-5787b56f-678d-4f04-826b-e6e6fb7b0962.png)

**Comment by SendNukez** [comment] 2021-10-07 05:35
hm, that's exactly the same as me, are you at all familiar with the chrome devtools and html / css?

**Comment by Wist9063** [comment] 2021-10-07 23:44
> 
> 
> hm, that's exactly the same as me, are you at all familiar with the chrome devtools and html / css?

Yes, I am.

**Comment by SendNukez** [comment] 2021-10-08 01:10
Could you maybe try to find out what the problem is then? Since this is not happening with my installation, I can't really do much myself.

**Comment by Projekt95** [comment] 2021-10-09 08:51
Changing the following fixed the position:

1. The container css class of the container (`<div class="GlueDropTarget GlueDropTarget--tracks personal-library" ...`):
From `GlueDropTarget GlueDropTarget--tracks personal-library` to `main-navBar-navBarItem`
2. the css class of the <a> inside the container 
From `main-collectionLinkButton-collectionLinkButton` to `link-subtle main-navBar-navBarLink` fixes the position.

Btw: Is there a reason why this one is the only div container in the list (other entries all have `<li>`)?

**Comment by SendNukez** [comment] 2021-10-09 13:41
So from what it looks like in the first screenshot, this might be caused by too much padding on the left. You could try to change the `padding-left` on the `.main-collectionLinkButton-collectionLinkButton`. I still don't get why this is only an issue for some people though.

As for the reason some of the sidebar items have different classes / tags, I don't know why that is. But what I do know is that it makes styling it a real hassle.

**Comment by Projekt95** [comment] 2021-10-09 17:13
I tried it with all extensions disabled but `dribbblish.js` and `dribbblish-dynamic.js` but the issue is still the same.

**Comment by SendNukez** [comment] 2021-10-10 03:00
I didn't even know you could stick the items to the top. I always hated that the liked songs would scroll. But that explains it. I can push a fix for this now finally. Thank you for your Investigation.

**Closed** 2021-10-10 03:02 UTC

**Comment by SendNukez** [comment] 2021-10-10 03:04
Should be fixed now. It'll be in the next Release. If you want to fix it now just replace your user.css with [this](https://github.com/JulienMaille/dribbblish-dynamic-theme/blob/main/user.css)
