### ISSUE TITLE
Crash-After-Latest-Update

### ISSUE THREAD

**Issue by vvirtues** [JulienMaille/dribbblish-dynamic-theme#182] opened 2022-02-28 14:21 UTC
**Describe the bug**
Infinite-load-after-latest-update

**To Reproduce**
1. get-new-update(powershell)

**Screenshots**

https://user-images.githubusercontent.com/81705406/155998053-2fe78991-ee6f-4bac-be17-24299300db21.mp4

**Desktop Setup**
- Operating System: Windows 11 21H2
- Spotify:N/A
- Spicetify: 2.1.9
- Dribbblish: Latest

**Logs**
N/A

**Comment by aliquis0001** [comment] 2022-02-28 20:39
Same issue here. Spicetify 2.1.9, Dribbblish Dynamic 4.1.2, Spotify 1.1.79.763.gc2965cdf

**Comment by JulienMaille** [comment] 2022-02-28 21:09
Do you use the marketplace?

**Comment by vvirtues** [comment] 2022-03-01 17:12
yes

**Comment by Amcio** [comment] 2022-03-01 17:13
I have marketplace installed and I had the same issue. Reverted to the old version for now. Devtools didn't even load fully so no errors, unless there is some other log?

**Comment by JulienMaille** [comment] 2022-03-01 19:13
I believe that marketplace is the root cause of this issue

**Comment by vvirtues** [comment] 2022-03-02 16:02
its-not

**Comment by JulienMaille** [comment] 2022-03-02 19:10
Have you tried without the marketplace ?

**Comment by IrepY** [comment] 2022-03-02 19:26
I tried it without the marketplace, it did not fix it

**Comment by vvirtues** [comment] 2022-03-02 19:36
same

**Comment by vvirtues** [comment] 2022-03-02 22:47
I realize that it loads the player and maybe lyrics, if left open after restore, but not anything else. If I use media controls, music still plays

**Comment by doongs** [comment] 2022-03-05 23:59
Getting a similar issue here, stuck at the "Just one moment..." loading screen. I've taken a small stab at running through the debugger, and it looks like it could be down to this chunk of code at 63 in expFeatures.js:

```
(function waitForRemoteConfigResolver() {
        let resolver = Spicetify.Platform?.RemoteConfigResolver;
        if (!resolver) {
            setTimeout(waitForRemoteConfigResolver, 500);
            return;
        }
```

Resulting in all three of these conditionals resolving to true on line 49 of Dribblish.js
```if (document.querySelector("#main") == null || Spicetify?.showNotification == undefined || !this.info.isReady()) return;```

**Comment by JulienMaille** [comment] 2022-03-13 08:53
> Spicetify.Platform is undefined resulting in all three of these conditionals resolving to true on line 49 of Dribblish.js `if (document.querySelector("#main") == null || Spicetify?.showNotification == undefined || !this.info.isReady()) return;`

@SendNukez What do you think?

**Comment by SendNukez** [comment] 2022-03-18 23:43
Sorry for the absence, I think this is fixed. At least it is for me on `Spotify v1.1.81`, `Spicetify v2.9.2` and `Dribbblish v4.1.3`. I'd investigate further, but the Devtools are broken atm.

**Comment by vvirtues** [comment] 2022-03-19 15:39
same here with latest update

**Comment by vvirtues** [comment] 2022-03-19 15:46
Actually, I'm getting an error here on `spicetify v2.9.2` with devtool at least showing something
![image](https://user-images.githubusercontent.com/81705406/159128094-e58c8aa9-e0b3-4fa1-90a9-cbea7ee71665.png)

**Comment by vvirtues** [comment] 2022-03-19 15:49
wait its not your fault. the new update isnt fully out yet so i'll wait

**Comment by doongs** [comment] 2022-03-22 23:51
After a full uninstall/reinstall of both spotify, spicetify, and dribblish everything seems to be working ok on my end. Both my Win11 and PopOS (Ubuntu) machines look good.

Could have been Spotify updating that changed things, not too sure.

@vvirtues try reinstalling your spotify client, that might fix your issue

**Closed** 2022-03-26 13:20 UTC
Labels: bug
