### ISSUE TITLE
[BUG] The now playing section shows multiple songs in a queue

### ISSUE THREAD

**Issue by Jnss98b** [JulienMaille/dribbblish-dynamic-theme#42] opened 2021-09-28 03:36 UTC
**Describe the bug**
The now playing section is supposed to show only the current song but it shows multiple following songs in a queue when you start skipping songs. I know you fixed this issue in another bug report but I can assure you I'm on the latest update and it's still happening
**To Reproduce**
Start playing music and skip

**Screenshots**
![image](https://user-images.githubusercontent.com/24306400/135018710-087e49e1-2d07-4756-9850-fcd2f005f505.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H1

**Comment by JulienMaille** [comment] 2021-09-28 05:37
Duplicate of #37

**Closed** 2021-09-28 05:37 UTC
