### ISSUE TITLE
Stuck at "Starting up..."

### ISSUE THREAD

**Issue by CrazyGoGo42** [JulienMaille/dribbblish-dynamic-theme#139] opened 2021-12-11 14:30 UTC
**Describe the bug**
I reinstalled Spotify/Spicetify to the latest versions and the following issue occurred.

**To Reproduce**
1. Reinstalled Spotify/Spicetify to their latest versions
1a. Opened powershell with admin privileges and typed "spicetify restore"
1b. Deleted the following folders: ".spicetify" and "spicetify-cli" from the User folder.
1c. Executed this command in the powershell "Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression"
2. Installed theme (using the install.ps1)
2a. Downloaded "dribbblish-dynamic-theme-main.zip" and "DribbblishDynamic_v4.1.1.zip"
2b. went to .spicetify/Themes and dragged the Theme-main in there folder in there
2c. added the v4.1.1 files to the themes directory (.js in the extensions folder)

**Issues:**
1. Theme graphics don't seem to load properly
2. Stuck at "Startung up..."

**Screenshots**
https://i.imgur.com/8oSqeg1.png

**Desktop Setup**
- Operating System: Windows 10 (21H2)
- Spotify: Spotify for Windows 1.1.74.631.g0b24d9ad
- Spicetify: 2.8.3
- Dribbblish: 4.1.1

``` xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/leaderboard
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2712035)
    at t.r.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2714619)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2321867
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2955910)
    at Is (https://xpui.app.spotify.com/vendor~xpui.js:29:2979642)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3194923)
    at ho (https://xpui.app.spotify.com/vendor~xpui.js:29:2925446)
    at As (https://xpui.app.spotify.com/vendor~xpui.js:29:2979421)
    at ws (https://xpui.app.spotify.com/vendor~xpui.js:29:2964300)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2963222)
c @ vendor~xpui.js:29
2vendor~xpui.js:29 The buttonLegacy prop has been deprecated. This prop will be removed soon. Please migrate to new button styles by removing this prop.
Read more: https://encore.spotify.net/web/whats-new/green-buttons/?format=web-js
i @ vendor~xpui.js:29
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/696.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/367.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-playlist.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```
Any help is welcome. I generally had issues before updating to latest dribbblish version in the past.

**Comment by JulienMaille** [comment] 2021-12-11 16:21
duplicate of #136

**Closed by JulienMaille** 2021-12-11 16:21 UTC
Labels: bug

**Comment by JulienMaille** [comment] 2021-12-13 16:01
Try `spicetify restore backup apply`
