### ISSUE TITLE
Dribbblish stops working

### ISSUE THREAD

**Issue by huhridge** [JulienMaille/dribbblish-dynamic-theme#122] opened 2021-11-26 05:13 UTC
**Describe the bug**
Usually after a song changes, Spotify freezes up, audio still plays, but Spotify becomes unresponsive, nothing shows up in the dev-tools.

**To Reproduce**

**Screenshots**
After relaunching Spotify nothing loads,
<img width="1440" alt="Screenshot 2021-11-25 at 21 10 04" src="https://user-images.githubusercontent.com/67046436/143530235-5e302226-63c5-4d4b-9758-e91671e7306b.png">
Nothing in dev-tools,
<img width="1440" alt="Screenshot 2021-11-25 at 21 10 13" src="https://user-images.githubusercontent.com/67046436/143530293-c28e8018-1e72-4d69-b16e-f933f785457e.png">

**Desktop Setup**
 - Operating System: MacOS 12.0.1
 - Spotify version: Spotify for macOS (Apple Silicon) 1.1.73.515.g85e282e2
 - Spicetify version: 2.8.3
 - Dribbblish version: 4.0.0

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtool` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
(Please paste here console logs or attach a screenshot)
```

**Comment by JulienMaille** [comment] 2021-11-26 06:47
Can you detaul how you have installed the theme ?

**Comment by huhridge** [comment] 2021-11-26 07:00
Downloaded the release, copied into Themes folder(renamed), copied js into extensions, added into config. It was working perfectly before 4.0.0

**Comment by JulienMaille** [comment] 2021-11-26 07:23
You need to remove the extra .js files that are no longer used. That's why we have a batch script for installation

**Comment by huhridge** [comment] 2021-11-26 07:33
There are no extra js files

**Comment by JulienMaille** [comment] 2021-11-26 19:12
Can you share the content of `config-xpui`?

**Comment by huhridge** [comment] 2021-11-26 19:19
`[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,

[Setting]
overwrite_assets        = 1
color_scheme            = base
inject_css              = 1
replace_colors          = 1
spotify_launch_flags    = 
check_spicetify_upgrade = 0
spotify_path            = /Applications/Spotify.app/Contents/Resources
prefs_path              = /Users/huhridge/Library/Application Support/Spotify/prefs
current_theme           = DribbblishDynamic

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
extensions            = popupLyrics.js|shuffle+.js|fullappDisplayxFAD.js|dribbblish-dynamic.js
custom_apps           = new-releases|lyrics-plusxFAD
sidebar_config        = 1
home_config           = 1
experimental_features = 1

; DO NOT CHANGE!
[Backup]
version = 1.1.73.515.g85e282e2
with    = 2.8.3`

**Comment by huhridge** [comment] 2021-11-26 19:20
```
[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,

[Setting]
overwrite_assets        = 1
color_scheme            = base
inject_css              = 1
replace_colors          = 1
spotify_launch_flags    = 
check_spicetify_upgrade = 0
spotify_path            = /Applications/Spotify.app/Contents/Resources
prefs_path              = /Users/huhridge/Library/Application Support/Spotify/prefs
current_theme           = DribbblishDynamic

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
extensions            = popupLyrics.js|shuffle+.js|fullappDisplayxFAD.js|dribbblish-dynamic.js
custom_apps           = new-releases|lyrics-plusxFAD
sidebar_config        = 1
home_config           = 1
experimental_features = 1

; DO NOT CHANGE!
[Backup]
version = 1.1.73.515.g85e282e2
with    = 2.8.3
```

**Comment by JulienMaille** [comment] 2021-11-26 19:35
I just noticed you did not share the "console" tab in dev tools, can you look for error messages there?

**Comment by huhridge** [comment] 2021-11-26 19:36
There's nothing there, it was empty

**Comment by JulienMaille** [comment] 2021-11-26 19:38
very weird, maybe check for a corrupted .js?

**Comment by SendNukez** [comment] 2021-11-26 23:15
It can't be empty, there has to be at least some warnings like:
![image](https://user-images.githubusercontent.com/29760988/143660599-335418f5-5706-46d0-b2c1-8dbbecf54be6.png)

**Comment by huhridge** [comment] 2021-11-27 12:30
its empty, take a look:
https://user-images.githubusercontent.com/67046436/143681357-6554a9b6-fd48-48ad-afc9-e8971189eb41.mov

**Comment by SendNukez** [comment] 2021-11-27 14:13
Huh, that's odd, could you try opening the console and then refreshing the page by right clicking somewhere in Spotify and clicking "Reload"?

**Comment by alixti** [comment] 2021-11-29 04:55
Try to [uninstall Dribbblish](https://github.com/JulienMaille/dribbblish-dynamic-theme#linuxmacos-bash-1), then run `spicetify clear` on Bash to remove all backups then run `spicetify upgrade` to update Spicetify if you had an old version of it and then [install the theme again](https://github.com/JulienMaille/dribbblish-dynamic-theme#linuxmacos-bash).

**Comment by huhridge** [comment] 2021-11-30 08:20
> Huh, that's odd, could you try opening the console and then refreshing the page by right clicking somewhere in Spotify and clicking "Reload"?

Clicking reloading does nothing

**Comment by huhridge** [comment] 2021-11-30 08:21
The weird part is that after changing the theme to something, and changing it back, it starts working, then it inevitably stops and I have to do it again, very weird

**Comment by JulienMaille** [comment] 2021-11-30 21:34
Can you try latest build?
[DribbblishDynamic_vDev-193953d.zip](https://github.com/JulienMaille/dribbblish-dynamic-theme/files/7629001/DribbblishDynamic_vDev-193953d.zip)

**Comment by huhridge** [comment] 2021-12-01 05:48
I'll try and let you know if it stops working.

**Comment by huhridge** [comment] 2021-12-01 05:55
just so you know, there are some bugs in the dev build, like the search setting not working, and dribbblish-loader staying even after everything has loaded

**Comment by HuangLinBao** [comment] 2021-12-01 18:35
I have stumbled upon this problem too....same pictures as the one OP sent...and I've followed the steps mentioned in the issue and no use
> Can you try latest build? [DribbblishDynamic_vDev-193953d.zip](https://github.com/JulienMaille/dribbblish-dynamic-theme/files/7629001/DribbblishDynamic_vDev-193953d.zip)

regarding this version after installation here is what I get



![image](https://user-images.githubusercontent.com/57255961/144293114-2d0039b4-f1f8-427f-91d6-2fc38ca43429.png)

**Comment by huhridge** [comment] 2021-12-02 05:42
<img width="1440" alt="Screenshot 2021-12-02 at 11 11 47" src="https://user-images.githubusercontent.com/67046436/144364569-ddb2e4cd-8908-4d1c-89d3-0d985979edb3.png">
same thing happened to me, nothing in dev tools like before

**Comment by MohamadFeeshar** [comment] 2021-12-11 17:12
![spotify issue](https://user-images.githubusercontent.com/23179816/145685425-46b06d77-8ad3-4f93-954a-2915e6d93127.PNG)

This is what I got in dev tools

**Comment by sesvio** [comment] 2021-12-12 04:39
![bugdynamic](https://user-images.githubusercontent.com/88248205/145700470-45631226-8b3a-430a-b15e-643258f71067.png)

I have the same problem for 8 hours now, I have re-installed Spotify, re-installed Spicetify and DribbblishDynamic but nothing seems to work. Is there a way to fix it?

Thank you.

**Comment by ps13g** [comment] 2021-12-12 15:25
<img width="1512" alt="Screen Shot 2021-12-12 at 8 23 36 AM" src="https://user-images.githubusercontent.com/84423124/145718343-78b73faf-90cb-4332-ba69-eaa6a9301b81.png">

Running into the same issue on MacOS with Dribbblish. Seems like its a combined spicetify and Dribbblish issue because 4.0.0 does not work properly either on the new version of Spotify.

**Comment by huhridge** [comment] 2021-12-13 18:02
I tried, with the latest release and the new css mappings, same issue as before

**Comment by ps13g** [comment] 2021-12-13 18:09
Can confirm running `spicetify restore backup apply` works and fixes the issue.
<img width="1512" alt="Screen Shot 2021-12-13 at 11 08 48 AM" src="https://user-images.githubusercontent.com/84423124/145865416-66916b0c-9957-46cf-bc71-6ec397be3b1c.png">

**Comment by diZzyc0de** [comment] 2021-12-14 13:53
HI, `spicetify restore backup apply` doesn't work for me, spotify stuck in "Just one moment..." for a while, but when i delete these line in the config file it works but i can not scroll on the sidebar. 

thx for any help i get :) 

```
[Patch]
;xpui.js_find_8008 = ,(\w+=)32,
;xpui.js_repl_8008 = ,${1}58
```

**Comment by JulienMaille** [comment] 2021-12-15 22:57
Does it stops after advertisements? or a specific track?

**Comment by HuangLinBao** [comment] 2021-12-16 17:16
For me it's working pretty fine after installing the new version
![image](https://user-images.githubusercontent.com/57255961/146418115-87db5c1a-cd06-4722-b979-3f01b0841369.png)

**Comment by JulienMaille** [comment] 2021-12-31 22:43
Closing since we don't have any way to reproduce it. Please reopen if you have additional details

**Closed by JulienMaille** 2021-12-31 22:43 UTC
Labels: bug
