### ISSUE TITLE
Theme changes to blue for a bit whenever I skip songs, happens on playlists only

### ISSUE THREAD

**Issue by arlooonie** [JulienMaille/dribbblish-dynamic-theme#185] opened 2022-03-04 06:39 UTC
**Describe the bug**
 As what the title says, it happens when I skim through songs, only on playlists but not on albums. 
**To Reproduce**
1.  Pull any playlist you have in your library
2. skip songs

**Screenshots**

https://user-images.githubusercontent.com/100902107/156711921-654676b7-b8fd-404b-8ca8-e6d16da585ff.mp4

**Desktop Setup**
- Operating System:  Windows 10
- Spotify:   1.1.80.699
- Spicetify:  2.9.2
- Dribbblish:  4.1.2

**Comment by JulienMaille** [comment] 2022-03-04 07:16
Duplicate of #179 ?

**Comment by arlooonie** [comment] 2022-03-05 05:15
maybe, but it's still a recurring error even tho I'm using the latest version which has the fix

**Comment by JulienMaille** [comment] 2022-04-24 08:49
Should be closed in latest builds

**Closed by JulienMaille** 2022-04-24 08:49 UTC
Labels: bug
