### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ArvindAROO** [JulienMaille/dribbblish-dynamic-theme#41] opened 2021-09-27 03:47 UTC
**Describe the bug**
The albums of recently played songs are stacking up instead of being replaced

**To Reproduce**
Play a number of songs from different albums and all of the albums played so far will be stacked when we go to next album
**Screenshots**
![image](https://user-images.githubusercontent.com/54891738/134842413-27b7c8fe-26bf-408c-be7b-7344562ecded.png)

![image](https://user-images.githubusercontent.com/54891738/134842694-8c13f6bc-a682-4efd-9e90-d2aaa3fc7731.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [10.0.19043 Build 19043]

**Logs**

```console
vendor~xpui.js:1 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2353172)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2355454)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2048746
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2595327)
    at As (https://xpui.app.spotify.com/vendor~xpui.js:29:2619179)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2793496)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564835)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2618958)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2603729)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2602651)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2565107
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2793496)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564835)
    at yi (https://xpui.app.spotify.com/vendor~xpui.js:29:2565052)
    at vi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564987)
    at Es (https://xpui.app.spotify.com/vendor~xpui.js:29:2603150)
    at rl (https://xpui.app.spotify.com/vendor~xpui.js:29:2629563)
    at render (https://xpui.app.spotify.com/vendor~xpui.js:29:2632674)
    at https://xpui.app.spotify.com/xpui.js:1:1033981
(anonymous) @ vendor~xpui.js:1
3vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-search.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/754.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/22.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-playlist.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/451.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```
![image](https://user-images.githubusercontent.com/54891738/134842585-52847843-ba78-4241-a5dd-e5ccdc152001.png)

**Comment by JulienMaille** [comment] 2021-09-27 07:03
duplicate of #37

**Closed by JulienMaille** 2021-09-27 07:03 UTC
