### ISSUE TITLE
[BUG] Album names stacking 

### ISSUE THREAD

**Issue by cjghost2000** [JulienMaille/dribbblish-dynamic-theme#38] opened 2021-09-26 17:22 UTC
**Describe the bug**
downloaded the new dribbblish-dynamic.js and every time i skipped a song the album name of each song would stack onto each other and eventually cover the screen in the accent colour, problems goes away if i download the dribbblish-dynamic.js file from 8 days ago

**To Reproduce**
Steps to reproduce the behaviour: skip songs

**Screenshots**
![image](https://user-images.githubusercontent.com/25965419/134817416-0d2b7e53-67a5-4620-8851-f2708f941a61.png)
![image](https://user-images.githubusercontent.com/25965419/134817543-43037ddb-6a04-4f32-ae6f-a7bb03b17a21.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Version 1.1.62.583

**Comment by JulienMaille** [comment] 2021-09-26 18:16
Duplicate of #37

**Closed by JulienMaille** 2021-09-26 18:16 UTC
