### ISSUE TITLE
Text Not Appearing when Sidebar is adjusted fully to the left

### ISSUE THREAD

**Issue by MyBigFan2** [JulienMaille/dribbblish-dynamic-theme#230] opened 2022-05-08 16:06 UTC
**Describe the bug**
Text do not render when sidebar is fully retracted

**To Reproduce**
1. Open Spotify
2. Push the sidebar to the leftmost position
3. (most) Text disappears

Idk if this will help but I reinstalled Spotify and Spicetify to convert from using normal Dribbblish to using DribbblishDynamic, I have been experiencing this issue since DribbblishDynamic v4.2.0 thinking its a problem with the newer version of Spotify 1.1.84 and expecting the issue to resolve when there's a new update.

**Screenshots**
![image](https://user-images.githubusercontent.com/27133275/167304468-03ed19fe-cf99-472b-a76b-1298c87a27f1.png)
Normal ^
![image](https://user-images.githubusercontent.com/27133275/167304481-49ae9987-f599-41a7-92b2-0558bb02c638.png)
Retracted Sidebar ^
(Also wondering if there's a way to get playlist icons on sidebar as well)

**Desktop Setup**
OS: Windows v10.0.19043
Spotify: v1.1.84.716
Spicetify: v2.9.8
Dribbblish: v4.2.1-d03d89b

**Logs**
![image](https://user-images.githubusercontent.com/27133275/167304809-2b850b9a-8043-407f-b990-4f312b086fd1.png)

**Comment by JulienMaille** [comment] 2022-05-08 16:11
Duplicate of #224

**Closed by JulienMaille** 2022-05-08 16:11 UTC
Labels: bug
