### ISSUE TITLE
Always loading after Spotify updated

### ISSUE THREAD

**Issue by youensChen** [JulienMaille/dribbblish-dynamic-theme#138] opened 2021-12-11 09:22 UTC
and I have updated to the latest version 4.1.1
![image](https://raw.githubusercontent.com/youensChen/picgo/main/img2/20211211171555.png)

**Comment by Davoleo** [comment] 2021-12-11 10:57
Likely duplicate of #136

**Closed** 2021-12-11 12:40 UTC
Labels: bug

**Comment by JulienMaille** [comment] 2021-12-13 16:01
Try `spicetify restore backup apply`
