### ISSUE TITLE
incorrect progress bar placement when using Spotify Connect

### ISSUE THREAD

**Issue by ChoogleGrome** [JulienMaille/dribbblish-dynamic-theme#24] opened 2021-07-16 05:31 UTC
![image](https://user-images.githubusercontent.com/28058286/125896802-8a729dec-99d1-44ac-9643-20a310b2a962.png)

**Comment by Davoleo** [comment] 2021-07-16 08:35
Duplicate of #16

**Closed** 2021-07-16 09:04 UTC
