### ISSUE TITLE
[BUG] The album name still duplicates

### ISSUE THREAD

**Issue by mikasodc** [JulienMaille/dribbblish-dynamic-theme#43] opened 2021-09-28 21:27 UTC
The album names start adding up on the now playing.

Steps to reproduce the behavior: Simply skip the music...

![image](https://user-images.githubusercontent.com/83371344/135167928-10256498-ab22-4a4f-9bed-500270ca47fe.png)

 - OS: Windows
 - Version 1.9

![image](https://user-images.githubusercontent.com/83371344/135168094-de146377-9c9c-4318-a9dc-daedfc605bc9.png)

**Comment by JulienMaille** [comment] 2021-09-28 21:43
duplicate of #37

**Closed by JulienMaille** 2021-09-28 21:43 UTC
